FROM ffeoe-1smr-2526

RUN apk add --no-cache nodejs npm chromium && \
    npm install -g mermaid-filter

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser

RUN echo '{"args":["--no-sandbox","--disable-setuid-sandbox"]}' > /puppeteer.json
ENV MERMAID_FILTER_PUPPETEER_CONFIG=/puppeteer.json
